# Used to display on your repository's actions page
name: McAfee Containers Workshop - Building and pushing a docker image to Amazon ECR
# Name of the GitHub event triggering the workflow
on: push
# Setup environment variables to provide configuration option and credentials via Github
env:
  AWS_DEFAULT_REGION: ap-southeast-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: example-container:${{ github.sha }}
#A workflow run is made up of one or more jobs. They run in parallel by default. Each job runs in an environment specified by runs-on.
#A job contains a sequence of tasks called steps. Steps can run commands, run setup tasks, or run an action in your repository, a public repository, or an action published in a Docker registry
jobs:
  build-and-push:
    name: Building and pushing image to AWS ECR
    runs-on: ubuntu-latest
    steps:
#Check out the master
    - name: Checkout
      uses: actions/checkout@master
#Setup our Amazon ECR in order to push our image to it
    - name: Setup ECR
      run: |
        $( aws ecr get-login --no-include-email )
#Build and tag the docker image. Notice that we are using the environment variables defined in env
    - name: Build and tag the image
      run: |
        docker build \
          -t $CONTAINER_IMAGE \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE ./app
#Run docker push to push the image built in the previous step to Amazon ECR
    - name: Push
      if: github.ref == 'refs/heads/master'
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE
